codecov:
  branch: main
  bot: SDETools
  notify:
    require_ci_to_pass: false

coverage:
  range: 0..80
  round: up
  precision: 2
  status:
    patch:
      default:
        target: 80

comment: off
